### PR TITLE
CI added

### PR DESCRIPTION
**Pull request by SomaGallai**
## Purpose
Provide CI pipeline for repo.

## Approach
Template.

### Open Questions and Pre-Merge TODOs
- [ ] Validate CI passes.

## Dependencies
N/A

## Disclaimers
N/A
 
## Learning
N/A

### CODE REVIEW

**Comment by dimaxano** [comment]
The changes you brought here, breaks the packages installation process.
Why did you created CMakeLists.txt and changed build type? This is a python package

**Comment by SomaGallai** [comment]
> The changes you brought here, breaks the packages installation process. Why did you created CMakeLists.txt and changed build type? This is a python package

Hey Dmitry, what do you mean by breaking the package installation, are you unavailable to build the package with the introduced change? The reason why I have introduced the CMakeLists and changed the build type was the CI/CD pipeline uses the official ROS2 packaging tool called Bloom, that requires a CMake installation process. So I have used the general process of introducing a C like building process while the package maybe python you can take a look at https://github.com/Box-Robotics/ros2_numpy as you can see this is the standard procedure. 

BUT if it does not build for you let me know and I will try to handle the situation with a hotfix.

**Comment by SomaGallai** [comment]
> The changes you brought here, breaks the packages installation process. Why did you created CMakeLists.txt and changed build type? This is a python package

Could you validate if the new change helps your case, when you have time.

**Comment by dimaxano** [comment]
Validated, now everything is fine, thank you

**Pull request merged**
